### ISSUE TITLE
Surefire Plugin видит не все тесты

### ISSUE THREAD

**Issue by kokokokokomi** [komisuomi/Java_11_Dependencies#3]
**Шаги для воспроизведения:**

- Запустить цикл clean.

- Запустить цикл verify.

**Ожидаемый результат:**
Все тесты проходят проверку.

**Фактический результат:**
Surefire Plugin видит только тест для Afisha.java. Тесты для репозитория и менеджера игнорируются.
![issue](https://user-images.githubusercontent.com/70074580/96442591-0a83fc80-1214-11eb-970a-a77d6bdc1f00.png)

**Сетевое окружение:**
ОС Windows 10, Java 11 version, Surefire Plugin ver 2.22.2

**Comment by AnyaYu** [comment]
The problem is that by default only tests with certain name patterns are included: https://maven.apache.org/surefire/maven-surefire-plugin/examples/inclusion-exclusion.html

**Comment by kokokokokomi** [comment]
Спасибо за помощь, проблема решена.
