### ISSUE TITLE
Не проходит тест удаление по ID

### ISSUE THREAD

**Issue by kokokokokomi** [komisuomi/Java_11_Dependencies#4]
**Шаги для воспроизведения:**

- Сделать автотест для метода public void removeById (по аналогии с методом и тестом с лекции).

- Попытаться удалить объект с существующим ID из массива.

**Ожидаемый результат:**
Тесты проходит проверку.

**Фактический результат:**
Ошибка: array contents differ at index [0], expected: <Afisha(id=3 ... )> but was: <Afisha(id=2 ...)

![issue2](https://user-images.githubusercontent.com/70074580/96443539-7450d600-1215-11eb-83ab-0ad477ac933a.png)

**Сетевое окружение:**
ОС Windows 10, Java 11 version, Surefire Plugin ver 2.22.2

**Comment by AnyaYu** [comment]
Вы ожидаете массив в обратном порядке, но repository.findAll() возвращает обычный массив. Разворот происходит уже в менеджере. Та же проблема и в других тестах.

**Comment by kokokokokomi** [comment]
Спасибо, исправлено.
